### ISSUE TITLE
Add gas relay docs and API

### ISSUE THREAD

**Issue by Genesis3800** [availproject/docs#469]
### Objective

Add gas relay service to docs.

### To-dos:

- [x] Use [this Github repo](https://github.com/availproject/gas-relay-service) to add an introduction page for gas relay service.
- [x] Use [this Github repo](https://github.com/availproject/gas-relay-service) to add an API reference for the gas relay service.
- [x] Use [this notion doc](https://www.notion.so/avail-project/Gas-Relay-API-and-Guidelines-1297b347ae724d5fbad1ab2e468670c6) for any additional context that might be needed
- [x] (**IMPORTANT !!!**) seems like some stuff may or may not be private/not meant for docs in some way. Keep up with Dan in that regard.
- [ ] @rac-sri will review, as this might require several iterations.
